### ISSUE TITLE
typecheck stubs and defaults

### ISSUE THREAD

**Issue by ferronn-dev** [wowless/wowless#224]

**Comment by ferronn-dev** [comment]
This is nontrivial to fix.
```yaml
AppearanceSourceInfo:
  categoryID:
    default: None
    type: number
```
That default is actually an enum value. This is a tools/docs artifact wherein we just dump all enums into `number`.
